apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-care-app
  template:
    metadata:
      labels:
        app: health-care-app
    spec:
      containers:
        - name: health-care-container
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8092
