apiVersion: v1
kind: Service
metadata:
  name: health-care-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: health-care-app
  ports:
    - port: 80          # Service port inside the cluster
      targetPort: 8082  # Pod port your app listens on
      nodePort: 31552   # External port on the node
      protocol: TCP
