apiVersion: v1
kind: Service
metadata:
  name: health-care-service
  namespace: default
spec:
  selector:
    app: health-care-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082     # <-- This should match app's port
      nodePort: 31552
